version: '3.1'
services:
  db_mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    command:
      - '--character-set-server=utf8'
      - '--collation-server=utf8_general_ci'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-data:/var/lib/mysql
